[package]
authors = ["kenan.sulayman"]
license = "MIT"
name = "heimdal"
version = "0.1.3"

[dependencies]
neon = "0.1.18"
rand = "0.3.15"
rust-crypto = "0.2.36"

[build-dependencies]
neon-build = "0.1.18"

[lib]
crate-type = ["dylib"]
name = "heimdal"
