[package]
authors = ["kenan.sulayman"]
license = "MIT"
name = "heimdal"
version = "0.1.3"

[build-dependencies]
neon-build = "0.1.22"

[dependencies]
neon = "0.1.22"
rand = "0.4.2"
rust-crypto = "0.2.36"

[lib]
crate-type = ["dylib"]
name = "heimdal"
